### ISSUE TITLE
Is the () after language name intentional ?

### ISSUE THREAD

**Issue by silentWatcher3** [devgg/gh-issues#14]
Attached the screenshot

<img width="226" alt="Contrib" src="https://user-images.githubusercontent.com/71167111/93669680-70655300-fab3-11ea-87b9-f9ac215147ef.png">

**Comment by AdityaGupta150** [comment]
If it's not intentional, i will like to work @silentWatcher3 ?

**Comment by silentWatcher3** [comment]
> 
> 
> If it's not intentional, i will like to work @silentWatcher3 ?

That's good, let's see if it is intentional 🤔

**Comment by devgg** [comment]
The empty parantheses are not intentional. This text is taken from Wikipedia and the parantheses should contain the International Phonetic Alphabet.

<img width="942" alt="Screen Shot 2020-10-02 at 18 35 39" src="https://user-images.githubusercontent.com/8250067/94947585-28e0bd00-04de-11eb-8d65-66ed2be723a2.png">
